#!/usr/bin/with-contenv /bin/bash

set -eo pipefail

[[ $DEBUG == true ]] && set -x

echo -e "$VNC_PASSWD\n$VNC_PASSWD\n\n" | sudo -u user vncpasswd
if [ ! -d /etc/vnc ]; then
    mkdir /etc/vnc
fi
echo 'openbox-session' > /etc/vnc/xstartup